version: '3.8'
services:
  web:
      build: ./
      container_name: web
      command: python main.py
      #gunicorn --bind 0.0.0.0:8000 main:app
      volumes:
        - ./:/usr/src/app/
      ports:
        - 8000:8000
      expose:
        - 8000
      env_file:
        - ./.env

  db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vsemeng

  nginx:
      image: nginx:1.23-alpine
      ports:
        - 80:80
      expose:
        - 8000
      depends_on:
        - web
      volumes:
        - ./static:/usr/src/app/static
        - ./services/nginx:/etc/nginx/conf.d
volumes:
      postgres_data: