version: '3.8'
services:
  web:
      build: ./
      container_name: web
      command: python main.py
      #gunicorn --bind 0.0.0.0:8000 main:app
      volumes:
        - ./:/usr/src/app/
      ports:
        - 8000:8000
      expose:
        - 8000
      env_file:
        - ./.env

  db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vsemeng

  nginx:
      image: nginx:1.23-alpine
      ports:
        - 80:80
        - 443:443
      restart: always
      expose:
        - 8000
      depends_on:
        - web
      volumes:
        - ./static:/usr/src/app/static
        - ./services/nginx:/etc/nginx/conf.d
        - ./certbot/www:/var/www/certbot/:ro
        - ./certbot/conf/:/etc/nginx/ssl/:ro

  certbot:
      image: certbot/certbot
      depends_on:
        - nginx
      container_name: certbot
      volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
      command: docker compose run --rm  certbot certonly --webroot --webroot-path /var/www/certbot/ -d vsemeng.ru
volumes:
      postgres_data:
