version: '3.8'
services:
  web:
      build: ./
      container_name: web
      command: flask db upgrade head
      command: gunicorn --bind 0.0.0.0:8000 main:app
      restart: always
      volumes:
        - ./:/usr/src/app/
      ports:
        - 8000:8000
      expose:
        - 8000
      depends_on:
        - db
      env_file:
        - ./.env

  db:
      image: postgres:13-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=vsemeng

  nginx:
      image: nginx:1.23-alpine
      ports:
        - 80:80
        - 443:443
      restart: always
      expose:
        - 8000
      depends_on:
        - web
      volumes:
        - ./static:/usr/src/app/static
        - ./services/nginx:/etc/nginx/conf.d/:ro
        - ./certbot/www:/var/www/certbot/:ro
        - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
volumes:
      postgres_data: