"""empty message

Revision ID: 323760759a6d
Revises: 4566310cf65c
Create Date: 2022-12-07 18:13:14.444668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '323760759a6d'
down_revision = '4566310cf65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('last_login_ip',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('current_login_ip',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('current_login_ip',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('last_login_ip',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
