"""empty message

Revision ID: 5a758c2b1bff
Revises: d295e3c09016
Create Date: 2022-12-09 02:04:12.557274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5a758c2b1bff"
down_revision = "d295e3c09016"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_lesson",
        sa.Column("user_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("lesson_id", mysql.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["lesson_id"], ["lesson.id"], name="user_lesson_ibfk_1"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="user_lesson_ibfk_2"),
        sa.PrimaryKeyConstraint("user_id", "lesson_id"),
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "lesson",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", mysql.VARCHAR(length=100), nullable=True),
        sa.Column("date_lessons", mysql.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
