"""empty message

Revision ID: 77cfa8a572b3
Revises: 6fc6a0a3f4f5
Create Date: 2022-12-09 23:08:37.620564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77cfa8a572b3'
down_revision = '6fc6a0a3f4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic_url', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pic_url')

    # ### end Alembic commands ###
