"""empty message

Revision ID: 7d7ddbdee8fa
Revises: 323760759a6d
Create Date: 2022-12-09 01:46:22.208466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7ddbdee8fa'
down_revision = '323760759a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('date_lessons', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_lessons',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lessons_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lessons_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'lessons_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lessons')
    op.drop_table('lessons')
    # ### end Alembic commands ###
